variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ANSIBLE_FORCE_COLOR: 'true'

stages:
  - build
  - test
  - checking
  
build:
  stage: build
  script:
    - make

test_lexer:
  stage: test
  script:
    - make unit_test_lexer

test_parser:
  stage: test
  script:
    - make unit_test_parser

test_orderer:
  stage: test
  script:
    - make unit_test_ordos

test_cfg:
  stage: test
  script:
    - make unit_test_cfg

test_trans:
  stage: test
  script:
    - make unit_test_tr
    
check_basictest:
  stage: checking
  script:
    - ./basictest.sh
    - ./optest.sh
    - ./controltest.sh